<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Espluque.Application\Espluque.Application.csproj" />
    <ProjectReference Include="..\Espluque.Contracts\Espluque.Contracts.csproj" />
    <ProjectReference Include="..\Util\Util.csproj" />
  </ItemGroup>

</Project>
