<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.10" />
		<PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="3.53.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="$(ContractsProjectPath)" />
		<ProjectReference Include="$(ModuleCommonsProjectPath)" />
		<ProjectReference Include="$(ThemingProjectPath)" />
		<ProjectReference Include="$(SevenZipProjectPath)" />
	</ItemGroup>

	<ItemGroup>
		<None Update="module.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<Target Name="CopyModuleToHost" AfterTargets="Build">
		<PropertyGroup>
			<HostModuleDirectory>$(ModuleOutputDirectory)$(AssemblyName)\</HostModuleDirectory>
		</PropertyGroup>

		<MakeDir Directories="$(HostModuleDirectory)" />

		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(HostModuleDirectory)" />
		<Copy SourceFiles="$(TargetDir)$(TargetName).pdb" DestinationFolder="$(HostModuleDirectory)" Condition="'$(Configuration)' == 'Debug'" />
		<Copy SourceFiles="$(ProjectDir)module.json" DestinationFolder="$(HostModuleDirectory)" />

		<Copy SourceFiles="$(TargetDir)Microsoft.Data.Sqlite.dll" DestinationFolder="$(HostModuleDirectory)" />
		<Copy SourceFiles="$(TargetDir)SQLitePCLRaw.batteries_v2.dll" DestinationFolder="$(HostModuleDirectory)" />
		<Copy SourceFiles="$(TargetDir)SQLitePCLRaw.core.dll" DestinationFolder="$(HostModuleDirectory)" />
		<Copy SourceFiles="$(TargetDir)SQLitePCLRaw.provider.e_sqlite3.dll" DestinationFolder="$(HostModuleDirectory)" />
		<Copy SourceFiles="$(TargetDir)runtimes\win-x64\native\e_sqlite3.dll" DestinationFolder="$(HostModuleDirectory)" />
	</Target>

</Project>