[TargetMachine]
"0x0000" = "IMAGE_FILE_MACHINE_UNKNOWN"
"0x0184" = "IMAGE_FILE_MACHINE_ALPHA"
"0x0284" = "IMAGE_FILE_MACHINE_ALPHA64"
"0x01D3" = "IMAGE_FILE_MACHINE_AM33"
"0x8664" = "IMAGE_FILE_MACHINE_AMD64"
"0x01C0" = "IMAGE_FILE_MACHINE_ARM"
"0xAA64" = "IMAGE_FILE_MACHINE_ARM64"
"0x01C4" = "IMAGE_FILE_MACHINE_ARMNT"
"0x0EBC" = "IMAGE_FILE_MACHINE_EBC"
"0x014C" = "IMAGE_FILE_MACHINE_I386"
"0x0200" = "IMAGE_FILE_MACHINE_IA64"
"0x6232" = "IMAGE_FILE_MACHINE_LOONGARCH32"
"0x6264" = "IMAGE_FILE_MACHINE_LOONGARCH64"
"0x9041" = "IMAGE_FILE_MACHINE_M32R"
"0x0266" = "IMAGE_FILE_MACHINE_MIPS16"
"0x0366" = "IMAGE_FILE_MACHINE_MIPSFPU"
"0x0466" = "IMAGE_FILE_MACHINE_MIPSFPU16"
"0x01F0" = "IMAGE_FILE_MACHINE_POWERPC"
"0x01F1" = "IMAGE_FILE_MACHINE_POWERPCFP"
"0x0166" = "IMAGE_FILE_MACHINE_R4000"
"0x5032" = "IMAGE_FILE_MACHINE_RISCV32"
"0x5064" = "IMAGE_FILE_MACHINE_RISCV64"
"0x5128" = "IMAGE_FILE_MACHINE_RISCV128"
"0x01A2" = "IMAGE_FILE_MACHINE_SH3"
"0x01A3" = "IMAGE_FILE_MACHINE_SH3DSP"
"0x01A6" = "IMAGE_FILE_MACHINE_SH4"
"0x01A8" = "IMAGE_FILE_MACHINE_SH5"
"0x01C2" = "IMAGE_FILE_MACHINE_THUMB"
"0x0169" = "IMAGE_FILE_MACHINE_WCEMIPSV2"

[MagicNumber]
"0x010B" = "PE32"
"0x020B" = "PE32+"

[CoffCharacteristics]
"0x0001" = "IMAGE_FILE_RELOCS_STRIPPED"
"0x0002" = "IMAGE_FILE_EXECUTABLE_IMAGE"
"0x0004" = "IMAGE_FILE_LINE_NUMS_STRIPPED"
"0x0008" = "IMAGE_FILE_LOCAL_SYMS_STRIPPED"
"0x0010" = "IMAGE_FILE_AGGRESSIVE_WS_TRIM"
"0x0020" = "IMAGE_FILE_LARGE_ADDRESS_AWARE"
"0x0040" = ""
"0x0080" = "IMAGE_FILE_BYTES_REVERSED_LO"
"0x0100" = "IMAGE_FILE_32BIT_MACHINE"
"0x0200" = "IMAGE_FILE_DEBUG_STRIPPED"
"0x0400" = "IMAGE_FILE_REMOVABLE_RUN_FROM_SWAP"
"0x0800" = "IMAGE_FILE_NET_RUN_FROM_SWAP"
"0x1000" = "IMAGE_FILE_SYSTEM"
"0x2000" = "IMAGE_FILE_DLL"
"0x4000" = "IMAGE_FILE_UP_SYSTEM_ONLY"
"0x8000" = "IMAGE_FILE_BYTES_REVERSED_HI"

[DllCharacteristics]
"0x0001" = ""
"0x0002" = ""
"0x0004" = ""
"0x0008" = ""
"0x0020" = "IMAGE_DLLCHARACTERISTICS_HIGH_ENTROPY_VA"
"0x0040" = "IMAGE_DLLCHARACTERISTICS_DYNAMIC_BASE"
"0x0080" = "IMAGE_DLLCHARACTERISTICS_FORCE_INTEGRITY"
"0x0100" = "IMAGE_DLLCHARACTERISTICS_NX_COMPAT"
"0x0200" = "IMAGE_DLLCHARACTERISTICS_NO_ISOLATION"
"0x0400" = "IMAGE_DLLCHARACTERISTICS_NO_SEH"
"0x0800" = "IMAGE_DLLCHARACTERISTICS_NO_BIND"
"0x1000" = "IMAGE_DLLCHARACTERISTICS_APPCONTAINER"
"0x2000" = "IMAGE_DLLCHARACTERISTICS_WDM_DRIVER"
"0x4000" = "IMAGE_DLLCHARACTERISTICS_GUARD_CF"
"0x8000" = "IMAGE_DLLCHARACTERISTICS_TERMINAL_SERVER_AWARE"

[SubSystem]
"0x0" = "IMAGE_SUBSYSTEM_UNKNOWN"
"0x1" = "IMAGE_SUBSYSTEM_NATIVE"
"0x2" = "IMAGE_SUBSYSTEM_WINDOWS_GUI"
"0x3" = "IMAGE_SUBSYSTEM_WINDOWS_CUI"
"0x5" = "IMAGE_SUBSYSTEM_OS2_CUI"
"0x7" = "IMAGE_SUBSYSTEM_POSIX_CUI"
"0x8" = "IMAGE_SUBSYSTEM_NATIVE_WINDOWS"
"0x9" = "IMAGE_SUBSYSTEM_WINDOWS_CE_GUI"
"0xA" = "IMAGE_SUBSYSTEM_EFI_APPLICATION"
"0xB" = "IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER"
"0xC" = "IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER"
"0xD" = "IMAGE_SUBSYSTEM_EFI_ROM"
"0xE" = "IMAGE_SUBSYSTEM_XBOX"
"0x10" = "IMAGE_SUBSYSTEM_WINDOWS_BOOT_APPLICATION"
