<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Espluque.Contracts\Espluque.Contracts.csproj" />
    <ProjectReference Include="..\Util\Util.csproj" />
  </ItemGroup>

</Project>
